[[account_types]]
id = "CRD"
name = "Credit Card"

[[account_types]]
id = "CUR"
name = "Current Account"

[[account_types]]
id = "SAV"
name = "Savings Account"

[[account_types]]
id = "ISA"
name = "ISA"