[HSBC_UK]
company = 'HSBC Bank UK'
[HSBC_UK.config]
    page_number = 1
    regions = [
        {top_left = [367, 64], bottom_right = [575, 130]}
    ]
    type = 'search'
    fields = [
        {field = 'website', pattern ='www\.hsbc\.co\.uk'},
    ]

[NATWEST_UK]
company = 'NatWest Bank UK'
[NATWEST_UK.config]
    page_number = 1
    regions = [
        {top_left = [367, 64], bottom_right = [575, 130]}
    ]
    type = 'search'
    fields = [
        {field = 'website', pattern ='www\.natwest\.co\.uk'},
    ]