[HSBC_UK]                                       # identifier for the bank includes location and a counter in case it's needed
name = "HSBC Bank UK"                           # friendly name for the bank
refs = ["www.hsbc.co.uk"]                       # a list of refs to identify the bank
refs_all = true                                 # true if all specified refs must be found, false will id the bank if any refs are found
page = 1                                        # number of the table to search - bank will usually appear in the 1st table (0)
refs_strip = true                               # when matching the ref, should we strip out spaces?

[NATWEST_UK]                             
name = "NatWest UK"                   
refs = ["www.natwest.co.uk"]               
refs_all = true                         
page = 1 
refs_strip = true