[specs_001]

[specs_001.sort_code]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = ' ', replacement = ''},
    {pattern = 'Sortcode', replacement = ''},
]
refs = [
    {table = 1, row = 8, cell = 1, re_search = '^[0-9]{2}-[0-9]{2}-[0-9]{2}'},
    {table = 1, row = 9, cell = 1, re_search = '^[0-9]{2}-[0-9]{2}-[0-9]{2}'},
]

[specs_001.account_number]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = ' ', replacement = ''},
    {pattern = 'AccountNumber', replacement = ''},
]
refs = [
    {table = 1, row = 8, cell = 1, re_search = '[0-9]{8}$'},
    {table = 1, row = 8, cell = 2, re_search = '^[0-9]{8}'},
    {table = 1, row = 9, cell = 1, re_search = '[0-9]{8}$'},
    {table = 1, row = 9, cell = 2, re_search = '^[0-9]{8}'},
]
[specs_001.account_name]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = 'Account Nam e', replacement = ''},
]
refs = [
    {table = 1, row = 8, cell = 0, re_search = '^[A-Z]+[a-zA-Z]+ [A-Z]+[a-zA-Z]+.*'},
    {table = 1, row = 9, cell = 0, re_search = '^[A-Z]+[a-zA-Z]+ [A-Z]+[a-zA-Z]+.*'},
]
[specs_001.opening_balance]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
]
refs = [
    {table = 0, row = 7, cell = 2, re_search = '^[0-9]*\.[0-9]{2}[D]?$'},
]
[specs_001.closing_balance]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
]
refs = [
    {table = 0, row = 10, cell = 2, re_search = '^[0-9]*\.[0-9]{2}[D]?$'},
]
[specs_001.payments_in]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
]
refs = [
    {table = 0, row = 8, cell = 2, re_search = '^[0-9]*\.[0-9]{2}$'},
]
[specs_001.payments_out]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
]
refs = [
    {table = 0, row = 9, cell = 2, re_search = '^[0-9]*\.[0-9]{2}$'},
]


[specs_002]

[specs_002.card_number]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs= false
refs = [
    {table = 1, row = 2, cell = 1, re_search = '^[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}$'},
    {table = 1, row = 2, cell = 2, re_search = '^[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}$'},
    {table = 1, row = 0, cell = 2, re_search = '^[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}$'},
    {table = 2, row = 2, cell = 2, re_search = '^[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}$'},
]

[specs_002.account_name]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs= false
refs = [
    {table = 1, row = 2, cell = 0, re_search = '^[A-Z]+[a-zA-Z]+ [A-Z]+[a-zA-Z]+.*'},
    {table = 2, row = 2, cell = 0, re_search = '^[A-Z]+[a-zA-Z]+ [A-Z]+[a-zA-Z]+.*'},
]

[specs_002.opening_balance]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
    {pattern = 'PreviousBalance', replacement = ''},
]
refs = [
    {table = 0, row = 12, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
    {table = 0, row = 13, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
]
[specs_002.closing_balance]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
    {pattern = 'NewBalance', replacement = ''},
]
refs = [
    {table = 0, row = 15, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
    {table = 0, row = 16, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
]
[specs_002.payments_in]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
    {pattern = 'Credits', replacement = ''},
]
refs = [
    {table = 0, row = 14, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
    {table = 0, row = 15, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
]
[specs_002.payments_out]
ref_type = 'cell_value'  # (cell_value, table_search, row_search)
re_subs = [
    {pattern = '^£', replacement = ''},
    {pattern = ' ', replacement = ''},
    {pattern = ',', replacement = ''},
    {pattern = '\n', replacement = ''},
    {pattern = 'Debits', replacement = ''},
]
refs = [
    {table = 0, row = 13, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
    {table = 0, row = 14, cell = 1, re_search = '^[0-9]*\.[0-9]{2}$'},
]