[HSBC_UK_CUR_STM_BAL]
statement_region = 'Current Account Balances'
type = 'table'
row_spacing = 7
header_rows = 1
data_rows = 5
locations = [
    {page_number = 1, top_left = [345, 180], bottom_right = [575, 294]}
]

[HSBC_UK_CUR_STM_INFO]
statement_region = 'Statement Info Table'

statement_type = 'HSBC UK Current Account'
    [HSBC_UK_CUR.header]
        [[HSBC_UK_CUR.header.configs]]
            config = 'Statement Balances'
            page_number = 1
            regions = [
                {top_left = [345, 180], bottom_right = [575, 294]}
            ]
            type = 'table'
            row_spacing = 7
            header_rows = 1
            data_rows = 5
            fields = [
                {field = 'opening_balance', cell = {row = 1, col = 1}, strip = ['£',' ',',','\n'], pattern ='^[0-9]*\.[0-9]{2}[D]?$', vital=true, type='float'},
                {field = 'payments_in', cell = {row = 2, col = 1}, strip = ['£',' ',',','\n'], pattern ='^[0-9]*\.[0-9]{2}[D]?$', vital=true, type='float'},
                {field = 'payments_out', cell = {row = 3, col = 1}, strip = ['£',' ',',','\n'], pattern ='^[0-9]*\.[0-9]{2}[D]?$', vital=true, type='float'},
                {field = 'closing_balance', cell = {row = 4, col = 1}, strip = ['£',' ',',','\n'], pattern ='^[0-9]*\.[0-9]{2}[D]?$', vital=true, type='float'},
            ]
            tests = [
                {test_desc = 'credits and debits match balance movement', assertion = "({closing_balance} - {opening_balance}) = ({payments_in} + ({payments_out} * -1))"}
            ]
        [[HSBC_UK_CUR.header.configs]]
            config = 'Statemnt Info'
            page_number = 1
            regions = [
                {top_left = [37, 325], bottom_right = [190, 360]}
            ]
            type = 'search'
            fields = [
                {field = 'statement_date', pattern ='^[1-3]?[0-9]\s[A-Z][a-z]{2,8}\sto\s[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$', type='str'},
            ]
        [[HSBC_UK_CUR.header.configs]]
            config = 'Account Info'
            page_number = 1
            regions = [
                {top_left = [37, 365], bottom_right = [575, 410]}
            ]
            type = 'table'
            header_rows = 1
            data_rows = 1
            fields = [
                {field = 'account_name', cell = {row = 1, col = 0}, pattern ='^[A-Z]+[a-z]*\s[A-Z]+[a-z]*.*$', vital=true, type='str'},
                {field = 'sortcode', cell = {row = 1, col = 1}, pattern ='^[0-9]{2}-[0-9]{2}-[0-9]{2}$', vital=true, type='str'},
                {field = 'account_number', cell = {row = 1, col = 2}, pattern ='^[0-9]{8}$', vital=true, type='str'},
            ]
    [HSBC_UK_CUR.page]
            [[HSBC_UK_CUR.page.configs]]
            config = 'Page Info'
            regions = [
                {top_left = [37, 365], bottom_right = [575, 410]},
                {top_left = [37, 140], bottom_right = [575, 191]}
            ]
            type = 'table'
            header_rows = 1
            data_rows = 1
            fields = [
                {field = 'sheet_number', cell = {row = 1, col = 3}, pattern ='^[0-9]+$', type='int'},
            ]
    [HSBC_UK_CUR.lines]

[HSBC_UK_SAV]
statement_type = 'HSBC UK Saving Account'
    [HSBC_UK_SAV.header]
        [[HSBC_UK_SAV.header.configs]]
        [[HSBC_UK_SAV.header.configs]]
        [[HSBC_UK_SAV.header.configs]]
    [HSBC_UK_SAV.page]
        [[HSBC_UK_SAV.page.configs]]
        [[HSBC_UK_SAV.page.configs]]
        [[HSBC_UK_SAV.page.configs]]
    [HSBC_UK_SAV.lines]
        [[HSBC_UK_SAV.lines.configs]]
        [[HSBC_UK_SAV.lines.configs]]
        [[HSBC_UK_SAV.lines.configs]]

[HSBC_UK_CRD]
statement_type = 'HSBC UK Credit Card'
    [HSBC_UK_CRD.header]
        [[HSBC_UK_CRD.header.configs]]
        [[HSBC_UK_CRD.header.configs]]
        [[HSBC_UK_CRD.header.configs]]
    [HSBC_UK_CRD.page]
        [[HSBC_UK_CRD.page.configs]]
        [[HSBC_UK_CRD.page.configs]]
        [[HSBC_UK_CRD.page.configs]]
    [HSBC_UK_CRD.lines]
        [[HSBC_UK_CRD.lines.configs]]
        [[HSBC_UK_CRD.lines.configs]]
        [[HSBC_UK_CRD.lines.configs]]

[NATWEST_UK_SAV]
statement_type = 'NATWEST UK Saving Account'
    [NATWEST_UK_SAV.header]
        [[NATWEST_UK_SAV.header.configs]]
        [[NATWEST_UK_SAV.header.configs]]
        [[NATWEST_UK_SAV.header.configs]]
    [NATWEST_UK_SAV.page]
        [[NATWEST_UK_SAV.page.configs]]
        [[NATWEST_UK_SAV.page.configs]]
        [[NATWEST_UK_SAV.page.configs]]
    [NATWEST_UK_SAV.lines]
        [[NATWEST_UK_SAV.lines.configs]]
        [[NATWEST_UK_SAV.lines.configs]]
        [[NATWEST_UK_SAV.lines.configs]]