[TR_001]
min_table_number = 0
table_spans_pages = false

[TR_002]
min_table_number = 1
table_spans_pages = true
header_line = ['Received By Us', 'Transaction Date', 'Details', '']
valid_transactions = [
    ['^[0-3][0-9]\s\w{3}\s[0-9]{2}$','^[0-3][0-9]\s\w{3}\s[0-9]{2}$','.*','^[0-9]*\.[0-9]{2}[CR]?$'],
]