from bank_statement_parser.modules.data import CurrencySpec

currency_dict: dict = {
    "GBP": {
        "name": "British Pound Sterling",
        "symbols": ["GBP", "£"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "USD": {
        "name": "United States Dollar",
        "symbols": ["USD", "$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "EUR": {
        "name": "Euro",
        "symbols": ["EUR", "EURO", "EUROS", "€"],
        "seperator_decimal": ",",
        "seperators_thousands": [".", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[,][\d]{2}$",
    },
    "PHP": {
        "name": "Philippine Peso",
        "symbols": ["PHP", "₱"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "JPY": {
        "name": "Japanese Yen",
        "symbols": ["JPY", "¥", "円"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 0,
        "pattern": r"^[\d]+$",
    },
    "CHF": {
        "name": "Swiss Franc",
        "symbols": ["CHF", "Fr", "SFr"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " ", "'"],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "AUD": {
        "name": "Australian Dollar",
        "symbols": ["AUD", "A$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "CAD": {
        "name": "Canadian Dollar",
        "symbols": ["CAD", "C$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "SGD": {
        "name": "Singapore Dollar",
        "symbols": ["SGD", "S$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "HKD": {
        "name": "Hong Kong Dollar",
        "symbols": ["HKD", "HK$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "AED": {
        "name": "UAE Dirham",
        "symbols": ["AED", "د.إ"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "SAR": {
        "name": "Saudi Riyal",
        "symbols": ["SAR", "﷼", "SR"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "CNY": {
        "name": "Chinese Yuan Renminbi",
        "symbols": ["CNY", "RMB", "元", "¥"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "NZD": {
        "name": "New Zealand Dollar",
        "symbols": ["NZD", "NZ$"],
        "seperator_decimal": ".",
        "seperators_thousands": [",", " "],
        "round_decimals": 2,
        "pattern": r"^[\d]+[.][\d]{2}$",
    },
    "IDR": {
        "name": "Indonesian Rupiah",
        "symbols": ["IDR", "Rp"],
        "seperator_decimal": ",",
        "seperators_thousands": [".", " "],
        "round_decimals": 0,
        "pattern": r"^[\d]+$",
    },
}

currency_spec = {k: CurrencySpec(**v) for k, v in currency_dict.items()}
