[NATWEST_UK]
company = 'NatWest Bank UK'
[NATWEST_UK.config]
    config = 'Company Info'
    locations = [
        {page_number = 1, top_left = [390, 295], bottom_right = [480, 310]},
        {page_number = 1, top_left = [45, 630], bottom_right = [565, 815]}
    ]
    field = {field = 'footer', vital=true, type="string", string_pattern ='National Westminster Bank'}