"""Generate documentation pages from source code.

Extends the original single-page generator to produce six documentation pages,
all auto-generated from source code using ``ast``, ``tokenize``, and regex
parsing.  Every output file carries a ``DO NOT EDIT`` header.

Pages generated
---------------
1. ``docs/guides/new-bank-config.md``   — Adding a New Bank (from data.py + TOML examples)
2. ``docs/reference/cli.md``            — CLI Reference (from cli.py argparse definitions)
3. ``docs/reference/python-api.md``     — Python API Reference (from __init__.py __all__ + docstrings)
4. ``docs/guides/anonymisation.md``     — Anonymisation Guide (from anonymise.py module docstring + function docstrings)
5. ``docs/guides/project-structure.md`` — Project Structure (from paths.py docstrings)
6. ``docs/guides/exports.md``           — Export Options (from reports_db.py)

Run from the repository root::

    python scripts/generate_docs.py
"""

from __future__ import annotations

import ast
import re
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (relative to repository root)
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SRC = _REPO_ROOT / "src" / "bank_statement_parser"
_MODULES = _SRC / "modules"
_DATA_PY = _MODULES / "data.py"
_CLI_PY = _SRC / "cli.py"
_INIT_PY = _SRC / "__init__.py"
_ANONYMISE_PY = _MODULES / "anonymise.py"
_PATHS_PY = _MODULES / "paths.py"
_REPORTS_DB_PY = _MODULES / "reports_db.py"
_CONFIG_DIR = _SRC / "project" / "config" / "import"
_HSBC_DIR = _CONFIG_DIR / "HSBC_UK"

# Output paths
_DOCS = _REPO_ROOT / "docs"
_OUT_BANK_CONFIG = _DOCS / "guides" / "new-bank-config.md"
_OUT_CLI = _DOCS / "reference" / "cli.md"
_OUT_API = _DOCS / "reference" / "python-api.md"
_OUT_ANONYMISE = _DOCS / "guides" / "anonymisation.md"
_OUT_PROJECT = _DOCS / "guides" / "project-structure.md"
_OUT_EXPORTS = _DOCS / "guides" / "exports.md"

_DO_NOT_EDIT = "<!-- DO NOT EDIT — this file is auto-generated by scripts/generate_docs.py -->"
_REGENERATE = "<!-- Regenerate with: python scripts/generate_docs.py -->"


# ---------------------------------------------------------------------------
# Data structures for extracted info
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class FieldInfo:
    """One field extracted from a dataclass in data.py."""

    name: str
    type_annotation: str
    status: str  # "ACTIVE" or "STUB"
    description: str  # cleaned-up inline comment text


@dataclass(slots=True)
class ClassInfo:
    """One dataclass extracted from data.py."""

    name: str
    docstring: str
    fields: list[FieldInfo]


@dataclass(slots=True)
class ArgInfo:
    """One CLI argument parsed from argparse calls in cli.py."""

    name: str  # e.g. "--pdfs" or "target"
    dest: str  # Python attribute name
    help_text: str
    default: str | None
    choices: list[str] | None
    action: str | None
    metavar: str | None
    is_positional: bool


@dataclass(slots=True)
class SubcommandInfo:
    """One CLI subcommand parsed from cli.py."""

    name: str
    help_text: str
    description: str
    arguments: list[ArgInfo]


@dataclass(slots=True)
class ApiSymbol:
    """One public symbol from __init__.py __all__."""

    name: str
    group: str  # comment header above the import
    import_source: str  # e.g. "bank_statement_parser.modules.statements"
    docstring: str  # first paragraph of the object's docstring
    kind: str  # "class", "function", "module", "constant"


@dataclass(slots=True)
class FunctionDoc:
    """Extracted documentation for a public function."""

    name: str
    signature: str
    docstring: str  # full Google-style docstring


# ---------------------------------------------------------------------------
# AST + tokenize extraction (for data.py — existing logic)
# ---------------------------------------------------------------------------


def _extract_field_comments(source: str) -> dict[tuple[int, str], tuple[str, str]]:
    """Extract inline comments for dataclass fields from source code.

    Uses ``tokenize`` to read the raw comments that ``ast`` discards.  Returns
    a mapping of ``(line_number, field_name)`` -> ``(status, description)``
    where *status* is ``"ACTIVE"`` or ``"STUB"`` and *description* is the
    cleaned comment text.

    For multi-line comments (continuation lines starting with ``#``), all
    lines are joined into a single description string.
    """
    lines = source.splitlines()
    result: dict[tuple[int, str], tuple[str, str]] = {}

    # Regex-scan lines for comments
    comment_map: dict[int, str] = {}
    for lineno_0, line in enumerate(lines):
        lineno = lineno_0 + 1
        m = re.search(r"#\s*(.*)", line)
        if m:
            comment_map[lineno] = m.group(1).strip()

    # Walk through lines to associate comments with fields.
    # Pattern: a field assignment line, then one or more comment lines below it.
    # Field lines look like:  "    field_name: Type" or "    field_name: Type = default"
    field_line_re = re.compile(r"^\s+(\w+)\s*:\s*(.+?)(?:\s*=\s*(.+))?$")

    i = 0
    while i < len(lines):
        line = lines[i]
        fm = field_line_re.match(line)
        if fm:
            field_name = fm.group(1)
            # Check if the next line(s) are comment lines
            comment_lines: list[str] = []
            j = i + 1
            while j < len(lines):
                stripped = lines[j].strip()
                if stripped.startswith("#"):
                    comment_lines.append(stripped.lstrip("# ").strip())
                    j += 1
                else:
                    break
            if comment_lines:
                full_comment = " ".join(comment_lines)
                # Extract status tag
                status_m = re.match(r"\[(\w+)\]\s*[—–-]\s*(.*)", full_comment)
                if status_m:
                    status = status_m.group(1)
                    desc = status_m.group(2).strip()
                else:
                    status = "ACTIVE"
                    desc = full_comment
                result[(i + 1, field_name)] = (status, desc)
        i += 1

    return result


def _extract_classes(source: str) -> list[ClassInfo]:
    """Parse data.py and return structured info for every dataclass."""
    tree = ast.parse(source)
    field_comments = _extract_field_comments(source)

    classes: list[ClassInfo] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue

        # Only process @dataclass-decorated classes
        is_dataclass = any(
            (isinstance(d, ast.Name) and d.id == "dataclass")
            or (isinstance(d, ast.Call) and isinstance(d.func, ast.Name) and d.func.id == "dataclass")
            for d in node.decorator_list
        )
        if not is_dataclass:
            continue

        docstring = ast.get_docstring(node) or ""
        fields: list[FieldInfo] = []

        for item in node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                fname = item.target.id
                # Reconstruct type annotation as source text
                ftype = ast.unparse(item.annotation) if item.annotation else "Any"
                # Clean up Optional display
                ftype = ftype.replace("Optional[", "").rstrip("]") if "Optional[" in ftype else ftype

                # Look up the comment for this field
                matched = None
                for (lineno, cfield), (status, desc) in field_comments.items():
                    if cfield == fname and abs(lineno - item.lineno) <= 1:
                        matched = (status, desc)
                        break
                if matched:
                    status, desc = matched
                else:
                    status, desc = "ACTIVE", ""

                fields.append(FieldInfo(name=fname, type_annotation=ftype, status=status, description=desc))

        classes.append(ClassInfo(name=node.name, docstring=docstring, fields=fields))

    return classes


# ---------------------------------------------------------------------------
# CLI argparse parser (for cli.py)
# ---------------------------------------------------------------------------


def _parse_cli_subcommands(source: str) -> list[SubcommandInfo]:
    """Parse cli.py AST to extract subcommand definitions from argparse calls.

    Walks the AST looking for ``add_parser()`` calls and their subsequent
    ``add_argument()`` calls, extracting all metadata needed to build a
    CLI reference page.
    """
    tree = ast.parse(source)
    subcommands: list[SubcommandInfo] = []

    # Find the main() function
    main_func = None
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "main":
            main_func = node
            break

    if main_func is None:
        return subcommands

    # Walk through main() body, tracking variable assignments to subparser names
    # We look for: var = subparsers.add_parser("name", ...)
    # Then: var.add_argument(...)
    subparser_vars: dict[str, SubcommandInfo] = {}

    for stmt in ast.walk(main_func):
        # Detect: var = subparsers.add_parser("name", help=..., description=...)
        if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
            var_name = stmt.targets[0].id
            call = stmt.value
            if isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute) and call.func.attr == "add_parser":
                # Extract subcommand name (first positional arg)
                cmd_name = ""
                if call.args and isinstance(call.args[0], ast.Constant):
                    cmd_name = str(call.args[0].value)

                help_text = _get_keyword_str(call, "help") or ""
                description = _get_keyword_str(call, "description") or ""

                info = SubcommandInfo(
                    name=cmd_name,
                    help_text=help_text,
                    description=description,
                    arguments=[],
                )
                subparser_vars[var_name] = info
                subcommands.append(info)

    # Now find all add_argument calls
    for stmt in ast.walk(main_func):
        if (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Call)
            and isinstance(stmt.value.func, ast.Attribute)
            and stmt.value.func.attr == "add_argument"
            and isinstance(stmt.value.func.value, ast.Name)
        ):
            var_name = stmt.value.func.value.id
            if var_name not in subparser_vars:
                continue

            call = stmt.value
            arg_info = _parse_add_argument(call)
            if arg_info:
                subparser_vars[var_name].arguments.append(arg_info)

    return subcommands


def _parse_add_argument(call: ast.Call) -> ArgInfo | None:
    """Extract an ArgInfo from a single add_argument() call AST node."""
    if not call.args:
        return None

    # Determine the argument name(s)
    names: list[str] = []
    for arg in call.args:
        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
            names.append(arg.value)

    if not names:
        return None

    is_positional = not names[0].startswith("-")
    # Use the longest --name as the display name
    name = max(names, key=len) if not is_positional else names[0]

    help_text = _get_keyword_str(call, "help") or ""
    action = _get_keyword_str(call, "action")
    metavar = _get_keyword_str(call, "metavar")
    dest = _get_keyword_str(call, "dest") or name.lstrip("-").replace("-", "_")

    # Default value
    default = None
    for kw in call.keywords:
        if kw.arg == "default":
            if isinstance(kw.value, ast.Constant):
                default = repr(kw.value.value)
            elif isinstance(kw.value, ast.Name):
                default = kw.value.id
            break

    # Choices
    choices = None
    for kw in call.keywords:
        if kw.arg == "choices":
            if isinstance(kw.value, ast.List):
                choices = []
                for elt in kw.value.elts:
                    if isinstance(elt, ast.Constant):
                        choices.append(str(elt.value))
            break

    return ArgInfo(
        name=name,
        dest=dest,
        help_text=help_text,
        default=default,
        choices=choices,
        action=action,
        metavar=metavar,
        is_positional=is_positional,
    )


def _get_keyword_str(call: ast.Call, keyword: str) -> str | None:
    """Extract a string-valued keyword argument from an AST Call node.

    Handles both simple string constants and parenthesised string
    concatenations (implicit joins across lines).
    """
    for kw in call.keywords:
        if kw.arg == keyword:
            if isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                return kw.value.value
            # Handle joined strings: ("foo " "bar") → JoinedStr or implicit concat
            if isinstance(kw.value, ast.JoinedStr):
                parts = []
                for v in kw.value.values:
                    if isinstance(v, ast.Constant):
                        parts.append(str(v.value))
                return "".join(parts)
    return None


# ---------------------------------------------------------------------------
# Public API parser (for __init__.py)
# ---------------------------------------------------------------------------


def _parse_public_api(source: str) -> list[ApiSymbol]:
    """Parse __init__.py to extract __all__ symbols with their group headers.

    Reads the comment headers above each import block to categorise symbols
    into groups (e.g. "Statement processing", "Errors", etc.).
    """
    tree = ast.parse(source)
    lines = source.splitlines()

    # Step 1: Build a map of symbol → import source module
    import_map: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                real_name = alias.asname or alias.name
                import_map[real_name] = node.module
        elif isinstance(node, ast.Import):
            for alias in node.names:
                real_name = alias.asname or alias.name
                import_map[real_name] = alias.name

    # Step 2: Parse __all__ list with group comments
    all_node = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    all_node = node.value
                    break

    if not isinstance(all_node, ast.List):
        return []

    # We need the source lines for __all__ to read the # comments
    # Find the line range of __all__
    all_start = all_node.lineno
    all_end = all_node.end_lineno or all_node.lineno

    symbols: list[ApiSymbol] = []
    current_group = "Ungrouped"

    for lineno in range(all_start, all_end + 1):
        line = lines[lineno - 1].strip()

        # Group comment: "# Statement processing"
        comment_match = re.match(r"#\s*(.+)", line)
        if comment_match and not line.startswith("#!"):
            current_group = comment_match.group(1).strip()
            continue

        # Symbol string: '"StatementBatch",' or '"__version__"'
        symbol_match = re.match(r'"(\w+)"', line)
        if symbol_match:
            sym_name = symbol_match.group(1)
            import_source = import_map.get(sym_name, "")

            symbols.append(
                ApiSymbol(
                    name=sym_name,
                    group=current_group,
                    import_source=import_source,
                    docstring="",  # filled in later by the generator
                    kind="",  # filled in later
                )
            )

    return symbols


# ---------------------------------------------------------------------------
# Module docstring extractor
# ---------------------------------------------------------------------------


def _extract_module_docstring(source: str) -> str:
    """Return the module-level docstring from a Python source string."""
    tree = ast.parse(source)
    return ast.get_docstring(tree) or ""


# ---------------------------------------------------------------------------
# Function docstring extractor
# ---------------------------------------------------------------------------


def _extract_function_docs(source: str, names: list[str]) -> list[FunctionDoc]:
    """Extract function signatures and docstrings from source for named functions.

    Args:
        source: Python source code string.
        names: List of function names to extract.

    Returns:
        List of FunctionDoc for each found function.
    """
    tree = ast.parse(source)
    results: list[FunctionDoc] = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name in names:
            docstring = ast.get_docstring(node) or ""
            # Build signature from AST
            sig = _build_signature(node)
            results.append(
                FunctionDoc(
                    name=node.name,
                    signature=sig,
                    docstring=docstring,
                )
            )

    return results


def _build_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Build a human-readable function signature from an AST FunctionDef."""
    args = node.args
    parts: list[str] = []

    # Regular positional args
    num_defaults = len(args.defaults)
    num_args = len(args.args)
    non_default_count = num_args - num_defaults

    for i, arg in enumerate(args.args):
        if arg.arg == "self" or arg.arg == "cls":
            continue
        annotation = f": {ast.unparse(arg.annotation)}" if arg.annotation else ""
        if i >= non_default_count:
            default_val = ast.unparse(args.defaults[i - non_default_count])
            parts.append(f"{arg.arg}{annotation} = {default_val}")
        else:
            parts.append(f"{arg.arg}{annotation}")

    # Return annotation
    ret = ""
    if node.returns:
        ret = f" -> {ast.unparse(node.returns)}"

    return f"{node.name}({', '.join(parts)}){ret}"


# ---------------------------------------------------------------------------
# Class docstring extractor
# ---------------------------------------------------------------------------


def _extract_class_docs(source: str, names: list[str]) -> dict[str, str]:
    """Extract class docstrings from source for named classes.

    Args:
        source: Python source code string.
        names: List of class names to extract.

    Returns:
        Mapping of class name to its docstring (first paragraph only).
    """
    tree = ast.parse(source)
    result: dict[str, str] = {}

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name in names:
            doc = ast.get_docstring(node) or ""
            # Take first paragraph
            if doc:
                first_para = doc.split("\n\n")[0].strip().replace("\n", " ")
                result[node.name] = first_para
            else:
                result[node.name] = ""

    return result


# ---------------------------------------------------------------------------
# TOML example loading
# ---------------------------------------------------------------------------


def _load_example(path: Path) -> str:
    """Read a TOML file and return its content as a fenced code block."""
    return path.read_text(encoding="utf-8").strip()


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def _field_table(fields: list[FieldInfo]) -> str:
    """Render a list of FieldInfo as a Markdown table."""
    rows = ["| Field | Type | Status | Description |", "| --- | --- | --- | --- |"]
    for f in fields:
        esc_desc = f.description.replace("|", "\\|")
        status_badge = f.status
        rows.append(f"| `{f.name}` | `{f.type_annotation}` | {status_badge} | {esc_desc} |")
    return "\n".join(rows)


def _class_section(ci: ClassInfo, heading_level: int = 3) -> str:
    """Render a ClassInfo as a Markdown section."""
    hashes = "#" * heading_level
    parts = [f"{hashes} `{ci.name}`", ""]
    if ci.docstring:
        # Take just the first paragraph of the docstring
        paragraphs = ci.docstring.split("\n\n")
        first_para = paragraphs[0].strip().replace("\n", " ")
        parts.append(first_para)
        parts.append("")
    if ci.fields:
        parts.append(_field_table(ci.fields))
        parts.append("")
    return "\n".join(parts)


def _docstring_to_markdown(docstring: str) -> str:
    """Convert a Google-style docstring to Markdown.

    Preserves section headers (Args, Returns, Raises, Example) as bold
    headings and indented content as code/text blocks.
    """
    if not docstring:
        return ""

    lines = docstring.splitlines()
    output: list[str] = []
    in_section = False
    section_name = ""

    for line in lines:
        stripped = line.strip()

        # Detect Google-style section headers (also handles RST-style "Example::")
        section_match = re.match(r"^(Args|Returns|Raises|Example|Note|Warning)s?::?\s*$", stripped)
        if section_match:
            section_name = section_match.group(1)
            if section_name == "Example":
                output.append("")
                output.append(f"**{section_name}:**")
                output.append("")
                output.append("```python")
            else:
                output.append("")
                output.append(f"**{section_name}:**")
                output.append("")
            in_section = True
            continue

        if in_section and section_name == "Example":
            if stripped == "" and output and output[-1] == "```python":
                continue  # skip blank line right after opening fence
            output.append(line.rstrip())
            continue

        if in_section and stripped:
            # Detect arg-style lines: "    param_name: description"
            arg_match = re.match(r"^\s{4,}(\w+)\s*(?:\(.*?\))?\s*:\s*(.+)", line)
            if arg_match:
                output.append(f"- `{arg_match.group(1)}` — {arg_match.group(2)}")
                continue
            # Continuation line
            arg_cont_match = re.match(r"^\s{8,}(.+)", line)
            if arg_cont_match:
                output.append(f"  {arg_cont_match.group(1).strip()}")
                continue

        if not stripped and in_section and section_name == "Example":
            output.append("```")
            in_section = False
            section_name = ""
            output.append("")
            continue

        if not stripped:
            in_section = False
            section_name = ""
            output.append("")
            continue

        output.append(stripped)

    # Close any unclosed example block
    if in_section and section_name == "Example":
        output.append("```")

    return "\n".join(output)


# ===================================================================
# Page 1: Adding a New Bank (existing generator, unchanged logic)
# ===================================================================


def generate_bank_config() -> str:
    """Generate the full 'Adding a New Bank' Markdown document."""
    source = _DATA_PY.read_text(encoding="utf-8")
    classes = _extract_classes(source)

    # Build a lookup by class name
    class_map = {c.name: c for c in classes}

    # Load TOML examples
    companies_toml = _load_example(_HSBC_DIR / "companies.toml")
    accounts_toml = _load_example(_HSBC_DIR / "accounts.toml")
    statement_types_toml = _load_example(_HSBC_DIR / "statement_types.toml")
    statement_tables_toml = _load_example(_HSBC_DIR / "statement_tables.toml")
    account_types_toml = _load_example(_CONFIG_DIR / "account_types.toml")
    standard_fields_toml = _load_example(_CONFIG_DIR / "standard_fields.toml")

    # --- Build document ---
    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# Adding a New Bank")
    w()
    w("This guide walks through the process of configuring bank_statement_parser to")
    w("parse PDF statements from a new bank. The configuration is entirely TOML-based")
    w("and does not require writing any Python code.")
    w()
    w("## Overview")
    w()
    w("Adding support for a new bank involves creating and editing several TOML files")
    w("that describe how to identify the bank's PDFs, locate tables on each page,")
    w("extract field values, and map them to standard output columns.")
    w()
    w("The configuration lives in two places:")
    w()
    w("| Location | Purpose |")
    w("| --- | --- |")
    w("| `project/config/import/<BANK_COUNTRY>/` | Bank-specific config folder (4 TOML files) |")
    w("| `project/config/import/account_types.toml` | Shared account type registry |")
    w("| `project/config/import/standard_fields.toml` | Shared standard field mappings |")
    w()
    w("### Bank config folder structure")
    w()
    w("Each bank has its own subfolder named in `SCREAMING_SNAKE_CASE` (e.g. `HSBC_UK`,")
    w("`TSB_UK`). A complete folder contains exactly four files:")
    w()
    w("| File | Purpose | Key Dataclass |")
    w("| --- | --- | --- |")
    w("| `companies.toml` | Bank identification (name + PDF detection rule) | [`Company`](#company) |")
    w("| `accounts.toml` | Account definitions (one per product/card type) | [`Account`](#account) |")
    w("| `statement_types.toml` | Statement layout definitions (header + lines extraction) | [`StatementType`](#statementtype) |")
    w("| `statement_tables.toml` | Physical table extraction rules (locations, fields, bookends) | [`StatementTable`](#statementtable) |")
    w()
    w("### Processing pipeline")
    w()
    w("Understanding the processing order helps when writing config:")
    w()
    w("1. **Company identification** — the `Company.config` extraction is run against page 1")
    w("   to determine which bank issued the PDF.")
    w("2. **Account identification** — each `Account.config` is tried until one matches,")
    w("   identifying the specific account product.")
    w("3. **Header extraction** — the `StatementType.header` configs run to extract")
    w("   statement-level metadata (dates, balances, account details).")
    w("4. **Lines extraction** — the `StatementType.lines` configs run per-page to extract")
    w("   transaction rows.")
    w("5. **Standard field mapping** — raw extracted fields are mapped to `STD_*` output")
    w("   columns via `standard_fields.toml`.")
    w("6. **Checks & balances** — opening balance + payments in - payments out = closing")
    w("   balance is validated.")
    w()

    # ----- Step 1: Account Types -----
    w("## Step 1: Register the Account Type")
    w()
    w("If your bank uses an account type not already in `account_types.toml`, add a new")
    w("entry. Most banks will use the existing types (`CRD`, `CUR`, `SAV`, `ISA`).")
    w()
    w("**File:** `project/config/import/account_types.toml`")
    w()
    w("```toml")
    w(account_types_toml)
    w("```")
    w()
    if "AccountType" in class_map:
        w(_class_section(class_map["AccountType"], heading_level=3))
    w()

    # ----- Step 2: Create folder -----
    w("## Step 2: Create the Bank Config Folder")
    w()
    w("Create a new subfolder under `project/config/import/` using the naming convention")
    w("`<BANK>_<COUNTRY>` in SCREAMING_SNAKE_CASE:")
    w()
    w("```")
    w("project/config/import/")
    w("  HSBC_UK/          # existing")
    w("  TSB_UK/           # existing")
    w("  NEWBANK_UK/       # <- your new folder")
    w("    companies.toml")
    w("    accounts.toml")
    w("    statement_types.toml")
    w("    statement_tables.toml")
    w("```")
    w()

    # ----- Step 3: companies.toml -----
    w("## Step 3: Define the Company")
    w()
    w("Create `companies.toml` in your new folder. This file identifies the bank by")
    w("extracting a distinguishing piece of text from page 1 of the PDF (typically a")
    w("website URL or bank name).")
    w()
    w("**Example** (`HSBC_UK/companies.toml`):")
    w()
    w("```toml")
    w(companies_toml)
    w("```")
    w()
    w("**How it works:** The `config` block defines a small extraction region on page 1.")
    w("The `field` spec extracts text from that region and checks it against")
    w("`string_pattern`. If the pattern matches, this company is selected. Multiple")
    w("`locations` can be provided — the pipeline tries each until one succeeds.")
    w()
    w("### Key dataclasses")
    w()
    for cls_name in ["Company", "Config", "Location", "Field"]:
        if cls_name in class_map:
            w(_class_section(class_map[cls_name], heading_level=4))

    # ----- Step 4: statement_tables.toml -----
    w("## Step 4: Define Statement Tables")
    w()
    w("Create `statement_tables.toml` to define how tables are physically extracted from")
    w("the PDF pages. This is usually the most complex configuration file, as it requires")
    w("understanding the precise layout of the bank's PDF statements.")
    w()
    w("Each table entry defines:")
    w()
    w("- **Where** on the page to look (bounding box coordinates, vertical column dividers)")
    w("- **What** fields to extract (column indices or cell addresses, data types, patterns)")
    w("- **How** to handle multi-row transactions (bookend detection, field merging)")
    w()
    w("### Table types")
    w()
    w("There are three table types, determined by the presence of `transaction_spec`:")
    w()
    w("| Type | Use Case | Field Addressing | Has `transaction_spec`? |")
    w("| --- | --- | --- | --- |")
    w("| `summary` | Account balances, totals | `cell = {row, col}` | No |")
    w("| `detail` | Account holder info, sort codes | `cell = {row, col}` | No |")
    w("| `transaction` | Transaction line items | `column = N` | Yes |")
    w()

    # Summary table example
    w("### Summary table example")
    w()
    w("A summary table extracts fixed values from known cell positions (e.g. opening")
    w("balance at row 1, column 1):")
    w()
    w("```toml")
    summary_lines: list[str] = []
    in_section = False
    for line in statement_tables_toml.splitlines():
        if line.startswith("[HSBC_UK_CUR_ACCT_SUM]"):
            in_section = True
        elif in_section and line.startswith("[") and "HSBC_UK_CUR_ACCT_SUM" not in line:
            break
        if in_section:
            summary_lines.append(line)
    w("\n".join(summary_lines).strip())
    w("```")
    w()

    # Transaction table example
    w("### Transaction table example")
    w()
    w("A transaction table extracts rows of variable length, using bookend detection")
    w("to identify where each transaction starts and ends:")
    w()
    w("```toml")
    txn_lines: list[str] = []
    in_section = False
    for line in statement_tables_toml.splitlines():
        if line.startswith("[HSBC_UK_CUR_TRANSACTIONS]"):
            in_section = True
        elif in_section and line.startswith("[") and "HSBC_UK_CUR_TRANSACTIONS" not in line:
            break
        if in_section:
            txn_lines.append(line)
    w("\n".join(txn_lines).strip())
    w("```")
    w()

    w("### Key dataclasses")
    w()
    for cls_name in [
        "StatementTable",
        "Location",
        "DynamicLineSpec",
        "Field",
        "Cell",
        "NumericModifier",
        "FieldOffset",
        "CurrencySpec",
        "TransactionSpec",
        "TransactionBookend",
        "FieldValidation",
        "MergeFields",
    ]:
        if cls_name in class_map:
            w(_class_section(class_map[cls_name], heading_level=4))

    # ----- Step 5: statement_types.toml -----
    w("## Step 5: Define Statement Types")
    w()
    w("Create `statement_types.toml` to define the extraction workflow for each distinct")
    w("statement layout. A single bank may have multiple statement types (e.g. current")
    w("account vs. credit card) if their PDF layouts differ.")
    w()
    w("Each statement type groups extraction into two sections:")
    w()
    w("- **`header`** — runs once per statement to extract metadata (dates, balances, account info)")
    w("- **`lines`** — runs per-page to extract transaction rows")
    w()
    w("Configs within each section either reference a `statement_table_key` from")
    w("`statement_tables.toml` or define an inline single-field extraction.")
    w()
    w("**Example** (`HSBC_UK/statement_types.toml`):")
    w()
    w("```toml")
    w(statement_types_toml)
    w("```")
    w()
    w("### Key dataclasses")
    w()
    for cls_name in ["StatementType", "ConfigGroup", "Config"]:
        if cls_name in class_map:
            w(_class_section(class_map[cls_name], heading_level=4))

    # ----- Step 6: accounts.toml -----
    w("## Step 6: Define Accounts")
    w()
    w("Create `accounts.toml` to define each account product offered by the bank. Each")
    w("account links together a company, an account type, and a statement type, plus")
    w("defines a PDF detection rule to identify which account a given statement belongs to.")
    w()
    w("**Example** (`HSBC_UK/accounts.toml` — first entry shown):")
    w()
    w("```toml")
    acct_lines: list[str] = []
    entry_count = 0
    for line in accounts_toml.splitlines():
        if line.startswith("[") and not line.startswith("[HSBC_UK_CRD_RCC"):
            if entry_count >= 1:
                break
        if line.startswith("[HSBC_UK_CRD_RCC"):
            entry_count = 1
        if entry_count >= 1:
            acct_lines.append(line)
    w("\n".join(acct_lines).strip())
    w("```")
    w()
    w("**Key fields:**")
    w()
    w("- `company_key` — must match a key in your `companies.toml`")
    w("- `account_type_key` — must match a key in the shared `account_types.toml` (e.g. `CRD`, `CUR`)")
    w("- `statement_type_key` — must match a key in your `statement_types.toml`")
    w("- `exclude_last_n_pages` — number of trailing pages to skip (terms & conditions, etc.)")
    w("- `config` — inline extraction rule to identify this account from page 1 of the PDF")
    w()
    w("### Key dataclasses")
    w()
    for cls_name in ["Account"]:
        if cls_name in class_map:
            w(_class_section(class_map[cls_name], heading_level=4))

    # ----- Step 7: standard_fields.toml -----
    w("## Step 7: Register Standard Field Mappings")
    w()
    w("Finally, add entries for your new statement type(s) to the shared")
    w("`standard_fields.toml`. This file maps bank-specific raw field names to")
    w("standardised output columns (`STD_*`).")
    w()
    w("For each `STD_*` field, add a new `std_refs` entry with your statement type's")
    w("name and the corresponding raw field name from your `statement_tables.toml`.")
    w()
    w("**File:** `project/config/import/standard_fields.toml`")
    w()
    w("**Example** (showing `STD_OPENING_BALANCE` with entries for multiple banks):")
    w()
    w("```toml")
    std_lines: list[str] = []
    in_section = False
    for line in standard_fields_toml.splitlines():
        if line.startswith("[STD_OPENING_BALANCE]"):
            in_section = True
        elif in_section and line.startswith("[") and "STD_OPENING_BALANCE" not in line:
            break
        if in_section:
            std_lines.append(line)
    w("\n".join(std_lines).strip())
    w("```")
    w()
    w("### Standard fields reference")
    w()
    w("The following standard fields must be mapped for each statement type. Fields")
    w("marked `vital = true` will raise a `ConfigError` if no mapping is found.")
    w()
    w("| Standard Field | Section | Type | Vital | Purpose |")
    w("| --- | --- | --- | --- | --- |")
    w("| `STD_STATEMENT_DATE` | header | date | Yes | Statement period end date |")
    w("| `STD_SORTCODE` | header | string | No | Bank sort code |")
    w("| `STD_ACCOUNT_NUMBER` | header | string | Yes | Account or card number |")
    w("| `STD_ACCOUNT_HOLDER` | header | string | No | Account holder name |")
    w("| `STD_OPENING_BALANCE` | header | numeric | Yes | Opening balance |")
    w("| `STD_CLOSING_BALANCE` | header | numeric | Yes | Closing balance |")
    w("| `STD_PAYMENTS_IN` | header | numeric | Yes | Total credits in period |")
    w("| `STD_PAYMENTS_OUT` | header | numeric | Yes | Total debits in period |")
    w("| `STD_TRANSACTION_DATE` | lines | date | Yes | Individual transaction date |")
    w("| `STD_TRANSACTION_TYPE` | lines | str | Yes | Payment type code |")
    w("| `STD_TRANSACTION_DESC` | lines | string | Yes | Transaction description |")
    w("| `STD_PAYMENT_IN` | lines | numeric | Yes | Credit amount per transaction |")
    w("| `STD_PAYMENT_OUT` | lines | numeric | Yes | Debit amount per transaction |")
    w()
    w("### `std_refs` entry options")
    w()
    w("Each `std_refs` entry supports the following options:")
    w()
    if "StdRefs" in class_map:
        w(_class_section(class_map["StdRefs"], heading_level=4))
    if "StandardFields" in class_map:
        w(_class_section(class_map["StandardFields"], heading_level=4))
    w()

    # ----- Checklist -----
    w("## Configuration Checklist")
    w()
    w("Use this checklist to verify your configuration is complete:")
    w()
    w("- [ ] Account type registered in `account_types.toml` (or existing type reused)")
    w("- [ ] Bank config folder created: `project/config/import/<BANK_COUNTRY>/`")
    w("- [ ] `companies.toml` — company key, name, and PDF detection rule")
    w("- [ ] `statement_tables.toml` — all table extraction rules (summary, detail, transaction)")
    w("- [ ] `statement_types.toml` — header and lines config groups referencing your table keys")
    w("- [ ] `accounts.toml` — account entries linking company, type, and statement type")
    w("- [ ] `standard_fields.toml` — `std_refs` entries added for all 13 standard fields")
    w("- [ ] Test with a real PDF: `bsp process --pdfs /path/to/statements`")
    w("- [ ] Verify checks & balances pass (opening + payments_in - payments_out = closing)")
    w()

    # ----- Dataclass Reference -----
    w("## Dataclass Reference")
    w()
    w("Complete reference for all configuration dataclasses defined in")
    w("`bank_statement_parser.modules.data`. Fields marked **STUB** are declared but")
    w("not currently read by the pipeline — they are reserved for future use.")
    w()

    order = [
        "Company",
        "Account",
        "AccountType",
        "StatementType",
        "ConfigGroup",
        "Config",
        "StatementTable",
        "Location",
        "DynamicLineSpec",
        "Field",
        "Cell",
        "FieldOffset",
        "NumericModifier",
        "CurrencySpec",
        "TransactionSpec",
        "TransactionBookend",
        "FieldValidation",
        "MergeFields",
        "StandardFields",
        "StdRefs",
        "Test",
    ]
    for name in order:
        if name in class_map:
            w(_class_section(class_map[name], heading_level=3))

    return "\n".join(doc)


# ===================================================================
# Page 2: CLI Reference
# ===================================================================


def generate_cli_reference() -> str:
    """Generate the CLI Reference page from cli.py argparse definitions."""
    source = _CLI_PY.read_text(encoding="utf-8")
    subcommands = _parse_cli_subcommands(source)

    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# CLI Reference")
    w()
    w("The `bsp` command-line tool provides subcommands for processing bank statement")
    w("PDFs and anonymising PDF files. Install the package to get the `bsp` entry point:")
    w()
    w("```bash")
    w("pip install uk-bank-statement-parser")
    w("```")
    w()

    for cmd in subcommands:
        w(f"## `bsp {cmd.name}`")
        w()
        if cmd.description:
            # Wrap long description text
            w(cmd.description)
            w()
        elif cmd.help_text:
            w(cmd.help_text)
            w()

        # Usage line
        usage_parts = [f"bsp {cmd.name}"]
        for arg in cmd.arguments:
            if arg.is_positional:
                usage_parts.append(arg.metavar or arg.name.upper())
            elif arg.action == "store_true":
                usage_parts.append(f"[{arg.name}]")
            elif arg.metavar:
                usage_parts.append(f"[{arg.name} {arg.metavar}]")
            elif arg.choices:
                usage_parts.append(f"[{arg.name} {{{','.join(arg.choices)}}}]")
            else:
                usage_parts.append(f"[{arg.name}]")
        w("```")
        w(" ".join(usage_parts))
        w("```")
        w()

        # Arguments table
        has_positional = any(a.is_positional for a in cmd.arguments)
        has_optional = any(not a.is_positional for a in cmd.arguments)

        if has_positional:
            w("### Positional arguments")
            w()
            w("| Argument | Description |")
            w("| --- | --- |")
            for arg in cmd.arguments:
                if arg.is_positional:
                    w(f"| `{arg.metavar or arg.name}` | {arg.help_text} |")
            w()

        if has_optional:
            w("### Options")
            w()
            w("| Option | Default | Description |")
            w("| --- | --- | --- |")
            for arg in cmd.arguments:
                if not arg.is_positional:
                    default_str = arg.default if arg.default is not None else ""
                    if arg.action == "store_true":
                        default_str = "off"
                    # Clean up default display
                    default_str = default_str.replace("None", "auto-detect").replace("'", "`")
                    if arg.choices:
                        choice_str = ", ".join(f"`{c}`" for c in arg.choices)
                        desc = f"{arg.help_text} Choices: {choice_str}."
                    else:
                        desc = arg.help_text
                    w(f"| `{arg.name}` | {default_str} | {desc} |")
            w()

    # Examples section
    w("## Examples")
    w()
    w("### Process all PDFs in a folder")
    w()
    w("```bash")
    w("bsp process --pdfs ~/statements")
    w("```")
    w()
    w("### Process with a specific project folder")
    w()
    w("```bash")
    w("bsp process --pdfs ~/statements --project ~/my_project")
    w("```")
    w()
    w("### Persist to database only, skip export")
    w()
    w("```bash")
    w("bsp process --pdfs ~/statements --data database --no-export")
    w("```")
    w()
    w("### Anonymise a single PDF")
    w()
    w("```bash")
    w("bsp anonymise statement.pdf")
    w("```")
    w()
    w("### Anonymise all PDFs in a folder")
    w()
    w("```bash")
    w("bsp anonymise ~/statements --folder")
    w("```")

    return "\n".join(doc)


# ===================================================================
# Page 3: Python API Reference
# ===================================================================


def generate_python_api() -> str:
    """Generate the Python API Reference page from __init__.py."""
    init_source = _INIT_PY.read_text(encoding="utf-8")
    symbols = _parse_public_api(init_source)

    # Read source files to get docstrings for each symbol
    source_cache: dict[str, str] = {}
    for sym in symbols:
        if sym.import_source and sym.import_source not in source_cache:
            # Convert module path to file path — try .py first, then __init__.py
            module_path = sym.import_source.replace(".", "/") + ".py"
            full_path = _REPO_ROOT / "src" / module_path
            if full_path.exists():
                source_cache[sym.import_source] = full_path.read_text(encoding="utf-8")
            else:
                # Try as a package (__init__.py)
                init_path = _REPO_ROOT / "src" / sym.import_source.replace(".", "/") / "__init__.py"
                if init_path.exists():
                    source_cache[sym.import_source] = init_path.read_text(encoding="utf-8")

    # Classify and get docstrings
    for sym in symbols:
        # Constants don't need source lookup
        if sym.name.startswith("__"):
            sym.kind = "constant"
            continue

        # Module-level imports (import ... as name) are modules, not functions
        if sym.name in ("db",):
            sym.kind = "module"
            module_source = source_cache.get(sym.import_source, "")
            if module_source:
                mod_doc = _extract_module_docstring(module_source)
                if mod_doc:
                    sym.docstring = mod_doc.split("\n\n")[0].strip().replace("\n", " ")
            continue

        source = source_cache.get(sym.import_source, "")
        if not source:
            sym.kind = "function"  # fallback for missing sources
            continue

        tree = ast.parse(source)
        found = False
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == sym.name:
                sym.kind = "class"
                node_doc = ast.get_docstring(node) or ""
                if node_doc:
                    sym.docstring = node_doc.split("\n\n")[0].strip().replace("\n", " ")
                found = True
                break
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == sym.name:
                sym.kind = "function"
                node_doc = ast.get_docstring(node) or ""
                if node_doc:
                    sym.docstring = node_doc.split("\n\n")[0].strip().replace("\n", " ")
                found = True
                break

        # If not found directly, follow re-exports (e.g. from sub.mod import name)
        if not found:
            for node in ast.walk(tree):
                if isinstance(node, ast.ImportFrom) and node.module:
                    for alias in node.names:
                        real_name = alias.asname or alias.name
                        if real_name == sym.name:
                            # Read the actual source module
                            reexport_path = _REPO_ROOT / "src" / (node.module.replace(".", "/") + ".py")
                            if reexport_path.exists():
                                reexport_source = reexport_path.read_text(encoding="utf-8")
                                orig_name = alias.name  # the original name in the source module
                                for rnode in ast.walk(ast.parse(reexport_source)):
                                    if isinstance(rnode, ast.ClassDef) and rnode.name == orig_name:
                                        sym.kind = "class"
                                        rdoc = ast.get_docstring(rnode) or ""
                                        if rdoc:
                                            sym.docstring = rdoc.split("\n\n")[0].strip().replace("\n", " ")
                                        found = True
                                        break
                                    if isinstance(rnode, (ast.FunctionDef, ast.AsyncFunctionDef)) and rnode.name == orig_name:
                                        sym.kind = "function"
                                        rdoc = ast.get_docstring(rnode) or ""
                                        if rdoc:
                                            sym.docstring = rdoc.split("\n\n")[0].strip().replace("\n", " ")
                                        found = True
                                        break
                            break

        if not found:
            sym.kind = "function"  # fallback

    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# Python API Reference")
    w()
    w("All public symbols are available from the top-level package:")
    w()
    w("```python")
    w("import bank_statement_parser as bsp")
    w("```")
    w()

    # Extract module docstring for quick start
    module_doc = _extract_module_docstring(init_source)
    # Pull out the quick start section
    if "Quick start" in module_doc:
        qs_start = module_doc.index("Quick start")
        qs_section = module_doc[qs_start:]
        # Find the end (next section with dashes)
        qs_lines = qs_section.splitlines()
        qs_code_lines: list[str] = []
        in_code = False
        for line in qs_lines:
            stripped = line.strip()
            if (
                stripped.startswith("import ")
                or stripped.startswith("from ")
                or stripped.startswith("batch")
                or stripped.startswith("flat")
                or stripped.startswith("bsp.")
                or stripped.startswith("#")
            ):
                in_code = True
            if in_code:
                if stripped and not re.match(r"^-+$", stripped) and not re.match(r"^\w.*\w$", stripped.rstrip(":")):
                    qs_code_lines.append(stripped)
                elif not stripped:
                    qs_code_lines.append("")
                else:
                    break

        if qs_code_lines:
            w("## Quick Start")
            w()
            w("```python")
            for line in qs_code_lines:
                w(line)
            w("```")
            w()

    # Group symbols by their group header
    current_group = ""
    for sym in symbols:
        if sym.group != current_group:
            current_group = sym.group
            w(f"## {current_group}")
            w()

        if sym.kind == "class":
            w(f"### `bsp.{sym.name}`")
            w()
            w(f"*class* — `{sym.import_source}`")
        elif sym.kind == "function":
            w(f"### `bsp.{sym.name}()`")
            w()
            w(f"*function* — `{sym.import_source}`")
        elif sym.kind == "module":
            w(f"### `bsp.{sym.name}`")
            w()
            w(f"*module* — `{sym.import_source}`")
        elif sym.kind == "constant":
            w(f"### `bsp.{sym.name}`")
            w()
            w("*constant*")
        else:
            w(f"### `bsp.{sym.name}`")
            w()

        if sym.docstring:
            w()
            w(sym.docstring)
        w()

    # Add DB backend detail section
    w("## DB Report Backend")
    w()
    w("`bsp.db` exposes report classes and export functions backed by the SQLite star-schema.")
    w()
    w("```python")
    w("# SQLite backend")
    w("flat = bsp.db.FlatTransaction().all.collect()")
    w("bsp.db.export_csv()")
    w("bsp.db.export_excel()")
    w("bsp.db.export_json()")
    w("bsp.db.export_reporting_data()")
    w("```")
    w()

    # Report classes available in both backends
    report_classes = [
        "FlatTransaction",
        "FactBalance",
        "DimTime",
        "DimStatement",
        "DimAccount",
        "FactTransaction",
        "GapReport",
    ]
    w("### Report classes")
    w()
    w("Available in `bsp.db`:")
    w()
    w("| Class | Description |")
    w("| --- | --- |")

    # Get docstrings from reports_db.py
    db_source = source_cache.get("bank_statement_parser.modules.reports_db", "")
    if not db_source and _REPORTS_DB_PY.exists():
        db_source = _REPORTS_DB_PY.read_text(encoding="utf-8")
    db_class_docs = _extract_class_docs(db_source, report_classes)

    class_descriptions = {
        "FlatTransaction": "Denormalised transaction view joining all dimensions.",
        "FactBalance": "Daily balance series per account (forward-filled).",
        "DimTime": "Calendar dimension — one row per date in the transaction range.",
        "DimStatement": "Statement dimension — one row per parsed PDF statement.",
        "DimAccount": "Account dimension — one row per unique account.",
        "FactTransaction": "Transaction fact table — one row per transaction.",
        "GapReport": "Gap detection report — flags missing statement periods.",
    }

    for cls_name in report_classes:
        desc = db_class_docs.get(cls_name) or class_descriptions.get(cls_name, "")
        w(f"| `{cls_name}` | {desc} |")
    w()

    # Export helpers
    w("### Export helpers")
    w()
    w("Available in `bsp.db`:")
    w()

    export_funcs = _extract_function_docs(db_source, ["export_csv", "export_excel", "export_json", "export_reporting_data"])
    for func in export_funcs:
        w(f"#### `{func.name}()`")
        w()
        w("```python")
        w(f"{func.signature}")
        w("```")
        w()
        if func.docstring:
            w(_docstring_to_markdown(func.docstring))
        w()

    return "\n".join(doc)


# ===================================================================
# Page 4: Anonymisation Guide
# ===================================================================


def generate_anonymisation_guide() -> str:
    """Generate the Anonymisation Guide from anonymise.py docstrings."""
    source = _ANONYMISE_PY.read_text(encoding="utf-8")
    module_doc = _extract_module_docstring(source)
    func_docs = _extract_function_docs(source, ["anonymise_pdf", "anonymise_folder"])

    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# Anonymisation Guide")
    w()

    # Parse the module docstring into sections
    if module_doc:
        sections: dict[str, list[str]] = {}
        current_section = "intro"
        sections[current_section] = []

        for line in module_doc.splitlines():
            # Detect RST section headers (line of dashes following a title)
            stripped = line.strip()
            if re.match(r"^-{3,}$", stripped):
                continue
            # Check if previous line was a section title
            section_title_match = re.match(r"^(\w[\w\s/()``]+)$", stripped)
            if section_title_match and stripped not in ("anonymise_pdf", "anonymise_folder"):
                # Only treat as section if it looks like a header (not too long)
                if len(stripped) < 60:
                    current_section = stripped
                    sections[current_section] = []
                    continue

            sections.setdefault(current_section, []).append(line)

        # Render intro
        if "intro" in sections:
            intro_text = "\n".join(sections["intro"]).strip()
            if intro_text:
                w(intro_text)
                w()

        # Render Scrambling rules
        if "Scrambling rules" in sections:
            w("## Scrambling Rules")
            w()
            for line in sections["Scrambling rules"]:
                stripped = line.strip()
                if stripped.startswith("* "):
                    w(f"- {stripped[2:]}")
                elif stripped:
                    w(stripped)
                else:
                    w()
            w()

        # Render Config file section
        config_key = None
        for key in sections:
            if "Config file" in key or "anonymise.toml" in key:
                config_key = key
                break

        if config_key:
            w("## Configuration File (`anonymise.toml`)")
            w()
            current_subsection = ""
            for line in sections[config_key]:
                stripped = line.strip()
                # Detect TOML section references
                subsec_match = re.match(r"^``(\[[\w_]+\])``$", stripped)
                if subsec_match:
                    current_subsection = subsec_match.group(1)
                    w(f"### `{current_subsection}`")
                    w()
                    continue
                if stripped.startswith("``") and stripped.endswith("``"):
                    # Inline code reference
                    w(f"`{stripped.strip('`')}`")
                elif stripped:
                    w(stripped)
                else:
                    w()
            w()

        # Render Implementation note
        if "Implementation note" in sections:
            w("## Implementation Notes")
            w()
            for line in sections["Implementation note"]:
                stripped = line.strip()
                if stripped:
                    w(stripped)
                else:
                    w()
            w()

    # Public API section from function docstrings
    w("## Public API")
    w()

    for func in func_docs:
        w(f"### `{func.name}()`")
        w()
        w("```python")
        w(func.signature)
        w("```")
        w()
        if func.docstring:
            w(_docstring_to_markdown(func.docstring))
        w()

    # CLI usage
    w("## CLI Usage")
    w()
    w("The `bsp anonymise` command wraps the Python API:")
    w()
    w("```bash")
    w("# Anonymise a single PDF")
    w("bsp anonymise statement.pdf")
    w()
    w("# Anonymise all PDFs in a folder")
    w("bsp anonymise ~/statements --folder")
    w()
    w("# Use a custom config file")
    w("bsp anonymise statement.pdf --config anonymise.toml")
    w()
    w("# Specify output location")
    w("bsp anonymise statement.pdf --output ~/anonymised/output.pdf")
    w("```")
    w()
    w("See the [CLI Reference](../reference/cli.md) for all available options.")

    return "\n".join(doc)


# ===================================================================
# Page 5: Project Structure Guide
# ===================================================================


def generate_project_structure() -> str:
    """Generate the Project Structure guide from paths.py docstrings."""
    source = _PATHS_PY.read_text(encoding="utf-8")

    # Extract key docstrings
    func_docs = _extract_function_docs(
        source,
        [
            "get_paths",
            "validate_or_initialise_project",
            "copy_project_folders",
        ],
    )

    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# Project Structure")
    w()
    w("Every bank_statement_parser project follows a standard directory layout.")
    w("The project folder contains all configuration, data, and export files for")
    w("a set of bank statements.")
    w()
    w("## Directory Layout")
    w()
    w("```")
    w("<project_root>/")
    w("  config/              # TOML configuration files")
    w("    HSBC_UK/           #   Bank-specific config subfolder")
    w("    TSB_UK/            #   (one per bank)")
    w("    account_types.toml #   Shared account type registry")
    w("    standard_fields.toml # Shared standard field mappings")
    w("    anonymise.toml     #   Anonymisation exclusion rules")
    w("  parquet/             # Parquet data files (permanent + temporary)")
    w("  database/")
    w("    project.db         # SQLite database (star-schema mart)")
    w("  export/")
    w("    csv/               # CSV report exports")
    w("    excel/             # Excel workbook exports")
    w("    json/              # JSON exports")
    w("  reporting/")
    w("    data/")
    w("      simple/          # Flat transactions CSV feed")
    w("      full/            # Star-schema CSV feeds")
    w("  statements/          # Source PDF copies (flat, one file per statement)")
    w("  log/")
    w("    debug/             # Per-statement debug output")
    w("```")
    w()

    w("## Project Lifecycle")
    w()
    w("When you run `bsp process`, the project is automatically validated or")
    w("initialised via `validate_or_initialise_project()`. The decision table is:")
    w()

    # Extract the decision table from the validate_or_initialise_project docstring
    validate_func = None
    for func in func_docs:
        if func.name == "validate_or_initialise_project":
            validate_func = func
            break

    if validate_func and validate_func.docstring:
        # Extract the decision table from the docstring
        in_table = False
        table_lines: list[str] = []
        for line in validate_func.docstring.splitlines():
            if line.strip().startswith("+--"):
                in_table = True
            if in_table:
                table_lines.append(line)
                if line.strip().startswith("+--") and len(table_lines) > 2:
                    # Check if this is the closing line
                    pass

        # Convert RST table to Markdown table
        if table_lines:
            headers: list[str] = []
            rows: list[list[str]] = []
            current_row: list[str] = []

            for line in table_lines:
                stripped = line.strip()
                if stripped.startswith("+"):
                    if current_row:
                        rows.append(current_row)
                        current_row = []
                elif stripped.startswith("|"):
                    cells = [c.strip() for c in stripped.split("|")[1:-1]]
                    if not current_row:
                        current_row = cells
                    else:
                        # Multi-line row: merge with previous
                        for i, cell in enumerate(cells):
                            if i < len(current_row) and cell:
                                current_row[i] = f"{current_row[i]} {cell}".strip()

            if current_row:
                rows.append(current_row)

            if rows:
                # First row is headers
                headers = rows[0]
                data_rows = rows[1:]

                w(f"| {' | '.join(headers)} |")
                w(f"| {' | '.join('---' for _ in headers)} |")
                for row in data_rows:
                    # Wrap exception names in backticks
                    formatted = []
                    for cell in row:
                        cell = re.sub(r":exc:`(\w+)`", r"`\1`", cell)
                        formatted.append(cell)
                    w(f"| {' | '.join(formatted)} |")
                w()

    w("## Python API")
    w()

    for func in func_docs:
        w(f"### `{func.name}()`")
        w()
        w("```python")
        w(func.signature)
        w("```")
        w()
        if func.docstring:
            w(_docstring_to_markdown(func.docstring))
        w()

    w("## CLI Integration")
    w()
    w("The `bsp process` command handles project creation automatically:")
    w()
    w("```bash")
    w("# Creates ./bsp_project/ if it doesn't exist")
    w("bsp process --pdfs ~/statements")
    w()
    w("# Use a custom project path")
    w("bsp process --pdfs ~/statements --project ~/my_project")
    w("```")
    w()
    w("See the [CLI Reference](../reference/cli.md) for all project-related options.")

    return "\n".join(doc)


# ===================================================================
# Page 6: Export Options Guide
# ===================================================================


def generate_exports_guide() -> str:
    """Generate the Export Options guide from report module docstrings."""
    db_source = _REPORTS_DB_PY.read_text(encoding="utf-8")

    db_funcs = _extract_function_docs(db_source, ["export_csv", "export_excel", "export_json", "export_reporting_data"])

    report_classes = [
        "FlatTransaction",
        "FactBalance",
        "DimTime",
        "DimStatement",
        "DimAccount",
        "FactTransaction",
        "GapReport",
    ]

    doc: list[str] = []

    def w(text: str = "") -> None:
        doc.append(text)

    w(_DO_NOT_EDIT)
    w(_REGENERATE)
    w()
    w("# Export Options")
    w()
    w("bank_statement_parser supports exporting report data in CSV, Excel, and JSON formats,")
    w("with two export presets and a dedicated reporting feed for external BI tools. Exports are")
    w("generated automatically by `bsp process` or can be triggered manually via the Python API.")
    w()
    w("## Export Presets")
    w()
    w("| Preset | Description |")
    w("| --- | --- |")
    w("| `simple` (default) | A single flat transactions table joining all dimensions. Best for spreadsheet analysis. |")
    w(
        "| `full` | Separate star-schema tables (accounts, calendar, statements, transactions, balances, gaps) for loading into an external database or BI tool. |"
    )
    w()
    w("## CLI Usage")
    w()
    w("```bash")
    w("# Default: export simple preset in both CSV and Excel from database")
    w("bsp process --pdfs ~/statements")
    w()
    w("# Export full star-schema tables as CSV only")
    w("bsp process --pdfs ~/statements --export-type full --export-format csv")
    w()
    w("# Skip export entirely")
    w("bsp process --pdfs ~/statements --no-export")
    w("```")
    w()
    w("| Option | Choices | Default | Description |")
    w("| --- | --- | --- | --- |")
    w("| `--export-type` | `simple`, `full` | `simple` | Export preset |")
    w("| `--export-format` | `excel`, `csv`, `json`, `all`, `reporting` | `all` | Output file format |")
    w("| `--no-export` | — | off | Skip the export step entirely |")
    w()

    w("## Python API")
    w()
    w("### Export functions")
    w()
    w("`bsp.db` provides `export_csv()`, `export_excel()`, `export_json()`, and `export_reporting_data()`:")
    w()

    for func in db_funcs:
        w(f"#### `{func.name}()`")
        w()
        w("```python")
        w(func.signature)
        w("```")
        w()
        if func.docstring:
            w(_docstring_to_markdown(func.docstring))
        w()

    w("### Usage examples")
    w()
    w("```python")
    w("import bank_statement_parser as bsp")
    w()
    w("# Export simple CSV from database backend (default project)")
    w("bsp.db.export_csv()")
    w()
    w("# Export full star-schema tables to Excel")
    w("bsp.db.export_excel(type='full')")
    w()
    w("# Export JSON")
    w("bsp.db.export_json()")
    w("")
    w("# Write stable CSV feeds for BI tools (simple + full presets)")
    w("bsp.db.export_reporting_data()")
    w("")
    w("# Export to a custom directory")
    w("from pathlib import Path")
    w("bsp.db.export_csv(folder=Path('~/exports'))")
    w("bsp.db.export_excel(path=Path('~/exports/report.xlsx'))")
    w("```")
    w()

    w("## Report Classes")
    w()
    w("All report classes expose a `.all` attribute containing a `pl.LazyFrame`.")
    w("Call `.collect()` to materialise the data.")
    w()
    w("```python")
    w("import bank_statement_parser as bsp")
    w()
    w("# Read from the DB backend")
    w("df = bsp.db.FlatTransaction().all.collect()")
    w("```")
    w()
    w("### Available classes")
    w()

    class_descriptions = {
        "FlatTransaction": "Denormalised transaction view joining all dimensions. One row per transaction with date, account, statement, and value columns.",
        "FactTransaction": "Transaction fact table. One row per transaction with foreign keys to dimension tables.",
        "FactBalance": "Daily balance series per account. Forward-filled from statement data to cover every calendar date.",
        "DimTime": "Calendar dimension. One row per date spanning the full transaction date range, with year, quarter, month, week, and day attributes.",
        "DimStatement": "Statement dimension. One row per parsed PDF statement with statement date, filename, and batch timestamp.",
        "DimAccount": "Account dimension. One row per unique account with company, type, number, sort code, and holder.",
        "GapReport": "Gap detection report. Flags periods where the closing balance of one statement does not match the opening balance of the next. Access `.gaps` for filtered gap rows only.",
    }

    for cls_name in report_classes:
        w(f"#### `{cls_name}`")
        w()
        desc = class_descriptions.get(cls_name, "")
        if desc:
            w(desc)
        w()

    w("## Output Files")
    w()
    w("### Simple preset")
    w()
    w("| Format | File | Contents |")
    w("| --- | --- | --- |")
    w("| CSV | `export/csv/transactions_table.csv` | Flat transaction table |")
    w("| Excel | `export/excel/transactions.xlsx` | Sheet: `transactions_table` |")
    w("| JSON | `export/json/transactions_table.json` | Flat transaction table (JSON array) |")
    w()
    w("### Full preset")
    w()
    w("| Format | Files / Sheets | Contents |")
    w("| --- | --- | --- |")
    w(
        "| CSV | `export/csv/` — `statement.csv`, `account.csv`, `calendar.csv`, `transactions.csv`, `balances.csv`, `gaps.csv` | Separate star-schema tables |"
    )
    w(
        "| Excel | `export/excel/transactions.xlsx` with sheets: `statement`, `account`, `calendar`, `transactions`, `balances`, `gaps` | Star-schema workbook |"
    )
    w(
        "| JSON | `export/json/` — `statement.json`, `account.json`, `calendar.json`, `transactions.json`, `balances.json`, `gaps.json` | Separate star-schema tables (JSON arrays) |"
    )
    w()
    w("### Reporting feed (`--export-format reporting`)")
    w()
    w("| Preset | Path | Contents |")
    w("| --- | --- | --- |")
    w("| `simple` | `reporting/data/simple/transactions_table.csv` | Flat transaction table |")
    w(
        "| `full` | `reporting/data/full/` — `statement.csv`, `account.csv`, `calendar.csv`, `transactions.csv`, `balances.csv`, `gaps.csv` | Star-schema CSV feeds |"
    )

    return "\n".join(doc)


# ---------------------------------------------------------------------------
# Main — write all pages
# ---------------------------------------------------------------------------

_PAGES: list[tuple[Path, Callable[[], str]]] = [
    (_OUT_BANK_CONFIG, generate_bank_config),
    (_OUT_CLI, generate_cli_reference),
    (_OUT_API, generate_python_api),
    (_OUT_ANONYMISE, generate_anonymisation_guide),
    (_OUT_PROJECT, generate_project_structure),
    (_OUT_EXPORTS, generate_exports_guide),
]


def main() -> None:
    """Generate all documentation pages."""
    for output_path, generator in _PAGES:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        content = generator()
        output_path.write_text(content, encoding="utf-8")
        print(f"Generated {output_path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    main()
