[HSBC_UK_CUR]
statement_type = 'HSBC UK Current Account'
    [HSBC_UK_CUR.header]
        [[HSBC_UK_CUR.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CUR_ACCT_SUM'

        [[HSBC_UK_CUR.header.configs]]
            config = 'Statement Info'
            location = {page_number=1, top_left = [37, 325], bottom_right = [190, 360]}
            field = {field = 'statement_date', pattern ='^[1-3]?[0-9]\s[A-Z][a-z]{2,8}\sto\s[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$', type='str'}

        [[HSBC_UK_CUR.header.configs]]
            config = 'Account Info'
            statement_table_key = 'HSBC_UK_CUR_ACCT_DET'

    [HSBC_UK_CUR.pages]
            [[HSBC_UK_CUR.pages.configs]]
            config = 'Page Info'
            locations = [
                {page_number = 1, top_left = [485, 388], bottom_right = [550, 410]}, #first page
                {top_left = [485, 163], bottom_right = [550, 185]} # all other pages
            ]
            field = {field = 'sheet_number', pattern ='^[0-9]+$', type='int'}

    [HSBC_UK_CUR.lines]

[HSBC_UK_SAV]
statement_type = 'HSBC UK Saving Account'
    [HSBC_UK_SAV.header]
        [[HSBC_UK_SAV.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CUR_ACCT_SUM'
            
        [[HSBC_UK_SAV.header.configs]]
            config = 'Statement Info'
            location = {page_number=1, top_left = [42, 350], bottom_right = [200, 385]}
            field = {field = 'statement_date', pattern ='^[1-3]?[0-9]\s[A-Z][a-z]{2,8}\sto\s[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$', type='str'}

        [[HSBC_UK_SAV.header.configs]]
            config = 'Account Info'
            statement_table_key = 'HSBC_UK_SAV_ACCT_DET'

    [HSBC_UK_SAV.page]
        [[HSBC_UK_SAV.pages.configs]]
            config = 'Page Info'
            locations = [
                {page_number = 1, top_left = [485, 408], bottom_right = [550, 425]}, #first page
                {top_left = [485, 163], bottom_right = [550, 185]} # all other pages
            ]
            field = {field = 'sheet_number', pattern ='^[0-9]+$', type='int'}

    [HSBC_UK_SAV.lines]

[HSBC_UK_CRD]
statement_type = 'HSBC UK Credit Card'
    [HSBC_UK_CRD.header]
        [[HSBC_UK_CRD.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CRD_ACCT_SUM'

        [[HSBC_UK_CRD.header.configs]]
            config = 'Statement Info'
            location = {page_number=1, top_left = [120, 470], bottom_right = [225, 500]}
            field = {field = 'statement_date', pattern ='^[0-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$', type='str'}

        [[HSBC_UK_CRD.header.configs]]
            config = 'Account Info'
            location = {page_number=2, top_left = [44, 174], bottom_right = [215, 200]}
            field = {field = 'account_name', pattern ='^[A-Z]+[a-z]*\s[A-Z]+[a-z]*.*$', vital=true, type='str'}

        [[HSBC_UK_CRD.header.configs]]
            config = 'Account Info'
            location = {page_number=2, top_left = [220, 175], bottom_right = [340, 197]}
            field = {field = 'card_number', pattern ='^[0-9]{4}\s[0-9]{4}\s[0-9]{4}\s[0-9]{4}\s?$', vital=true, type='str'}

    [HSBC_UK_CRD.page]
        [[HSBC_UK_CRD.pages.configs]]
            config = 'Page Info'
            locations = [
                {page_number = 1, top_left = [480, 470], bottom_right = [590, 500]}, #first page
                {page_number = 2, top_left = [475, 145], bottom_right = [590, 185]}, #first page
                {top_left = [460, 80], bottom_right = [590, 130]} # all other pages
            ]
            field = {field = 'sheet_number', pattern ='^Sheet[\s]*number[\s]*[0-9]+[\s]*of[\s]*[0-9]+$', type='str'}
    [HSBC_UK_CRD.lines]
        [[HSBC_UK_CRD.lines.configs]]
        [[HSBC_UK_CRD.lines.configs]]
        [[HSBC_UK_CRD.lines.configs]]

[NATWEST_UK_SAV]
statement_type = 'NATWEST UK Saving Account'
    [NATWEST_UK_SAV.header]
        [[NATWEST_UK_SAV.header.configs]]
        [[NATWEST_UK_SAV.header.configs]]
        [[NATWEST_UK_SAV.header.configs]]
    [NATWEST_UK_SAV.page]
        [[NATWEST_UK_SAV.pages.configs]]
        [[NATWEST_UK_SAV.pages.configs]]
        [[NATWEST_UK_SAV.pages.configs]]
    [NATWEST_UK_SAV.lines]
        [[NATWEST_UK_SAV.lines.configs]]
        [[NATWEST_UK_SAV.lines.configs]]
        [[NATWEST_UK_SAV.lines.configs]]