[HSBC_UK_CUR_ACCT_SUM]
type = "summary"
statement_table = 'Account Summary'
table_columns = 2
table_rows = 4
row_spacing = 7
locations = [
    {page_number=1, top_left = [345, 180], bottom_right = [575, 300], vertical_lines = [360, 475, 475, 550], dynamic_last_vertical_line = {image_id = 0, image_location_tag = "x1"}, allow_text_failover = true},
]
fields = [
    {field = 'opening_balance', cell = {row = 1, col = 1}, vital=true, type = 'numeric', numeric_currency ="GBP", numeric_modifier = {suffix = "D", multiplier = -1}},
    {field = 'payments_in', cell = {row = 2, col = 1}, vital=true, type = 'numeric', numeric_currency ="GBP"},
    {field = 'payments_out', cell = {row = 3, col = 1}, vital=true, type = 'numeric', numeric_currency ="GBP"},
    {field = 'closing_balance', cell = {row = 4, col = 1}, vital=true, type = 'numeric', numeric_currency ="GBP", numeric_modifier = {suffix = "D", multiplier = -1}},
]

[HSBC_UK_CUR_ACCT_DET]
type = "detail"
statement_table = 'Account Details'
table_columns = 4
table_rows = 2
locations = [
    {page_number = 1, top_left = [37, 365], bottom_right = [575, 410]},
]
fields = [
    {field = 'account_name', cell = {row = 1, col = 0}, vital = true, type = "string", string_pattern ='^[A-Z]+[a-z]*\s[A-Z]+[a-z]*.*$'},
    {field = 'sortcode', cell = {row = 1, col = 1}, vital=true, type = "string", string_pattern ='^[0-9]{2}-[0-9]{2}-[0-9]{2}$'},
    {field = 'account_number', cell = {row = 1, col = 2}, vital=true, type = "string", string_pattern ='^[0-9]{8}$'},
]

[HSBC_UK_SAV_ACCT_DET]
type = "detail"
statement_table = 'Account Details'
table_columns = 4
table_rows = 2
locations = [
    {page_number = 1, top_left = [37, 390], bottom_right = [575, 430], try_shift_down = 15},
]
fields = [
    {field = 'account_name', cell = {row = 1, col = 0}, vital=true, type = "string", string_pattern ='^[A-Z]+[a-z]*\s[A-Z]+[a-z]*.*$'},
    {field = 'sortcode', cell = {row = 1, col = 1}, vital=true, type = "string", string_pattern ='^[0-9]{2}-[0-9]{2}-[0-9]{2}$'},
    {field = 'account_number', cell = {row = 1, col = 2}, vital=true, type = "string", string_pattern ='^[0-9]{8}$'},
]

[HSBC_UK_CRD_ACCT_SUM]
type = "summary"
statement_table = 'Account Summary'
header_text = "Account Summary"
remove_header = true
row_spacing = 7
locations = [
    {page_number=1, top_left = [335, 180], bottom_right = [575, 380], vertical_lines = [360, 475, 475, 550], allow_text_failover = true},
]
fields = [
    {field = 'credit_limit', cell = {row = 0, col = 1}, vital=false, type = "numeric", numeric_currency = "GBP"},
    {field = 'apr', cell = {row = 1, col = 1}, vital=false, type = "string", string_pattern ='^[0-9]*\.[0-9]{1}[%]?$'},
    {field = 'previous_balance', cell = {row = 2, col = 1}, vital=false, type = "numeric", numeric_currency = "GBP", numeric_modifier = {suffix = "D", multiplier = -1.0000}},
    {field = 'debits', cell = {row = 3, col = 1}, vital=true, type = "numeric", numeric_currency = "GBP"},
    {field = 'credits', cell = {row = 4, col = 1}, vital=true, type = "numeric", numeric_currency = "GBP"},
    {field = 'new_balance', cell = {row = 5, col = 1}, vital=true, type = "numeric", numeric_currency = "GBP", numeric_modifier = {suffix = "D", multiplier = -1.0000}},
    {field = 'transaction_balance', cell = {row = 6, col = 1}, vital=true, type = "numeric", numeric_currency = "GBP", numeric_modifier = {suffix = "D", multiplier = -1.0000}},
    {field = 'minimum_payment', cell = {row = 7, col = 1}, vital=false, type = "numeric", numeric_currency = "GBP"}
]

[HSBC_UK_CRD_TRANSACTIONS]
type = "transaction"
statement_table = 'Transactions'
table_columns = 4
locations = [
    {vertical_lines = [52, 105, 105, 185, 185, 475, 475, 560], dynamic_last_vertical_line = {image_id = 1, image_location_tag = "x1"}},
]
fields = [
    {field = 'received_by_us', column = 0, vital=false, type = "string", string_pattern ='^[0-3][0-9]\s?[A-Z][a-z]{2}\s?[0-3][0-9]$'},
    {field = 'transaction_date', column = 1, vital=false, type = "string", string_pattern ='^[0-3][0-9]\s?[A-Z][a-z]{2}\s?[0-3][0-9]$'},
    {field = 'details', column = 2, vital=true, type = "string", string_pattern ='.+', string_max_length = 100},
    {field = 'amount', column = 3, vital=true, type = "numeric", numeric_currency = "GBP", numeric_modifier = {suffix = "CR", multiplier = -1.0000}},
    # {field = 'interest', column = 2, vital=false, type = "string", numeric_currency = "GBP", string_pattern ='^TOTAL[\S]?INTEREST[\S]?CHARGED', value_offset = {rows_offset = 0, cols_offset = 1, type = "numeric", vital=false, numeric_currency = "GBP"}},
]
delete_success_false = true
delete_cast_success_false = true
delete_rows_with_missing_vital_fields = true

[HSBC_UK_CRD_TRANSACTIONS.transaction_spec]
# transaction_bookends = {start_fields = ['received_by_us','transaction_date','details','amount'], min_non_empty_start = 4, end_fields = ['received_by_us','transaction_date','details','amount'], min_non_empty_end = 4, sticky_fields = ['interest']}
transaction_bookends = [
    {start_fields = ['received_by_us','transaction_date','details','amount'], min_non_empty_start = 4, end_fields = ['received_by_us','transaction_date','details','amount'], min_non_empty_end = 4},
    {start_fields = ['details','amount'], min_non_empty_start = 2, end_fields = ['details','amount'], min_non_empty_end = 2, extra_validation_start = {field = 'details', pattern = '^TOTAL[\S]?INTEREST[\S]?CHARGED'}},
]

[HSBC_UK_CUR_TRANSACTIONS]
type = "transaction"
statement_table = 'Transactions'
table_columns = 6
locations = [
    {vertical_lines = [50, 100, 100, 130, 130, 320, 320, 400, 400, 480, 480, 555]},
]
fields = [
    {field = 'date', column = 0, vital=false, type = "string", string_pattern ='^[0-3][0-9]\s?[A-Z][a-z]{2}\s?[0-3][0-9]$'},
    {field = 'payment_type', column = 1, vital=false, type = "string", string_pattern ='(^[A-Z0-9]{1,3}$)|(^[)]{3}$)'},
    {field = 'details', column = 2, vital=true, type = "string", string_pattern ='.+', string_max_length = 100},
    {field = '£_paid_out', column = 3, vital=false, type = "numeric", numeric_currency = "GBP"},
    {field = '£_paid_in', column = 4, vital=false, type = "numeric", numeric_currency = "GBP"},
    {field = '£_balance', column = 5, vital=false, type = "numeric", numeric_currency = "GBP", numeric_modifier = {suffix = "D", multiplier = -1.0000}},
]
delete_success_false = true
delete_cast_success_false = true
delete_rows_with_missing_vital_fields = true

[HSBC_UK_CUR_TRANSACTIONS.transaction_spec]
transaction_bookends = [
    {start_fields = ['payment_type','details'], min_non_empty_start = 2, end_fields = ['£_paid_out','£_paid_in'], min_non_empty_end = 1}
]
fill_forward_fields = ['date','payment_type']
merge_fields = {fields=['details'], separator=' | '}