[HSBC_UK_CUR]
statement_type = 'HSBC UK Current Account'
    [HSBC_UK_CUR.header]
        [[HSBC_UK_CUR.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CUR_ACCT_SUM'

        [[HSBC_UK_CUR.header.configs]]
            config = 'Statement Info'
            locations = [
                {page_number=1, top_left = [37, 325], bottom_right = [290, 385]}
                ]
            field = {field = 'statement_date', vital=true, type = "string", string_pattern ='^[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s(\d{4}\s)?to\s[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$'}

        [[HSBC_UK_CUR.header.configs]]
            config = 'Account Info'
            statement_table_key = 'HSBC_UK_CUR_ACCT_DET'

    [HSBC_UK_CUR.lines]
        [[HSBC_UK_CUR.lines.configs]]
            config = 'Transaction Lines'
            statement_table_key = 'HSBC_UK_CUR_TRANSACTIONS'

[HSBC_UK_SAV]
statement_type = 'HSBC UK Saving Account'
    [HSBC_UK_SAV.header]
        [[HSBC_UK_SAV.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CUR_ACCT_SUM'
            
        [[HSBC_UK_SAV.header.configs]]
            config = 'Statement Info'
            locations = [{page_number=1, top_left = [37, 325], bottom_right = [290, 385]}]
            field = {field = 'statement_date', vital=true, type = "string", string_pattern ='^[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s(\d{4}\s)?to\s[1-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$'}

        [[HSBC_UK_SAV.header.configs]]
            config = 'Account Info'
            statement_table_key = 'HSBC_UK_SAV_ACCT_DET'

    [HSBC_UK_SAV.lines]
        [[HSBC_UK_SAV.lines.configs]]
            config = 'Transaction Lines'
            statement_table_key = 'HSBC_UK_CUR_TRANSACTIONS'

[HSBC_UK_CRD]
statement_type = 'HSBC UK Credit Card'
    [HSBC_UK_CRD.header]
        [[HSBC_UK_CRD.header.configs]]
            config = 'Statement Balances'
            statement_table_key = 'HSBC_UK_CRD_ACCT_SUM'

        [[HSBC_UK_CRD.header.configs]]
            config = 'Statement Info'
            locations = [{page_number=1, top_left = [120, 470], bottom_right = [250, 500]}]
            field = {field = 'statement_date', vital=true, type = "string", string_pattern ='^[0-3]?[0-9]\s[A-Z][a-z]{2,8}\s[0-9]{4}$'}

        [[HSBC_UK_CRD.header.configs]]
            config = 'Account Info'
            locations = [{page_number=2, top_left = [44, 174], bottom_right = [215, 200]}]
            field = {field = 'account_name', vital=true, type = "string", string_pattern ='^[A-Z]+[a-z]*\s[A-Z]+[a-z]*.*$'}

        [[HSBC_UK_CRD.header.configs]]
            config = 'Account Info'
            locations = [{page_number=2, top_left = [220, 175], bottom_right = [340, 197]}]
            field = {field = 'card_number', vital=true, type = "string", string_pattern ='^[0-9]{4}\s[0-9]{4}\s[0-9]{4}\s[0-9]{4}\s?$'}

    [HSBC_UK_CRD.lines]
        [[HSBC_UK_CRD.lines.configs]]
            config = 'Transaction Lines'
            statement_table_key = 'HSBC_UK_CRD_TRANSACTIONS'
