[TR_001]
fixed_area = true
#area_spec = ["0, 0, 595, 841"]
area_spec = ["330, 677, 570, 542"]
fixed_column = false
#column_spec = ["110, 137, 335, 395, 475"]
specific_columns = true
min_table_number = 2
table_spans_pages = false
transaction_spans_lines = true
header_line = ['Received By Us', 'Transaction Date', 'Details', '']
valid_transactions = [
    ['^[0-3][0-9]\s\w{3}\s[0-9]{2}$','^[0-3][0-9]\s\w{3}\s[0-9]{2}$','.*','^[0-9]*\.[0-9]{2}[CR]?$'],
]


[TR_002]
fixed_area = false
fixed_columns = false
min_table_number = 1
table_spans_pages = true
transaction_spans_lines = false
header_line = ['Received By Us', 'Transaction Date', 'Details', '']
valid_transactions = [
    ['^[0-3][0-9]\s\w{3}\s[0-9]{2}$','^[0-3][0-9]\s\w{3}\s[0-9]{2}$','.*','^[0-9]*\.[0-9]{2}[CR]?$'],
]